################################################################################
##                                                                            ##
##  Ansible Tower Playbook                                                    ##
##  Name:        Deploy-Apache.yml                                            ##
##  Created by:  Matthew Kimler and Robert Nelson                             ##
##  Website:     www.iarchive.com                                             ##
##                                                                            ##
################################################################################

---
- name: This sets up an httpd webserver
  hosts: ec2
  become: yes
  tasks:
  - name: Wait for port 22 to become open on the host
    wait_for:
      port: 22
  - name: Install the httpd rpm
    yum: name=httpd
  - name: start the httpd service
    service: name=httpd state=started
